### ISSUE TITLE
.getDateTime() loses sync

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_Swarm_Satellite_Arduino_Library#22]
Howdy,

I've observed that the Swarm modem can lose its date and time sync when making direct calls to `mySwarm.getDateTime(&dateTime);`.

In this case, all unsolicited messages are disabled. It appears there was a communication timeout, which I believe means there was no $DT message to query, and afterwards, the modem lost its sync and was never able to recover.

I've observed similar behaviour when the $DT unsolicited message was enabled but unsure if they are related. I'll continue to test.

Cheers,
Adam

```
10:28:28.261 -> waitForResponse: Panic! _swarmBacklog is full!
10:28:28.261 -> sendCommandWithResponse: <====
10:28:28.261 -> getDateTime returned: 2022/6/6 14:28:28
10:28:33.273 -> sendCommandWithResponse: ====>
10:28:33.273 -> sendCommand: Command: $DT @*70
10:28:33.273 -> 
10:28:33.273 -> waitForResponse: $DT 2022
10:28:33.273 -> waitForResponse: Panic! _swarmBacklog is full!
10:28:33.273 -> waitForResponse: 060
10:28:33.273 -> waitForResponse: Panic! _swarmBacklog is full!
10:28:33.273 -> waitForResponse: 614
10:28:33.273 -> waitForResponse: Panic! _swarmBacklog is full!
10:28:33.273 -> waitForResponse: 28
10:28:33.273 -> waitForResponse: Panic! _swarmBacklog is full!
10:28:33.273 -> waitForResponse: 33,
10:28:33.273 -> waitForResponse: Panic! _swarmBacklog is full!
10:28:33.273 -> waitForResponse: V*4
10:28:33.273 -> waitForResponse: Panic! _swarmBacklog is full!
10:28:33.273 -> waitForResponse: 7
10:28:33.273 -> 
10:28:33.273 -> waitForResponse: Panic! _swarmBacklog is full!
10:28:33.273 -> sendCommandWithResponse: <====
10:28:33.273 -> getDateTime returned: 2022/6/6 14:28:33
10:28:38.260 -> sendCommandWithResponse: ====>
10:28:38.260 -> sendCommand: Command: $DT @*70
10:28:38.260 -> 
10:28:39.266 -> sendCommandWithResponse: <====
10:28:39.266 -> Swarm communication error: 3 : Communication timeout
10:28:44.271 -> sendCommandWithResponse: ====>
10:28:44.271 -> sendCommand: Command: $DT @*70
10:28:44.271 -> 
10:28:44.271 -> waitForResponse: $DT 20220606142838,V*4c <------- ***Date and time sync lost***
10:28:44.271 -> 
10:28:44.271 -> waitForResponse: Panic! _swarmBacklog is full!
10:28:44.271 -> sendCommandWithResponse: <====
10:28:44.271 -> getDateTime returned: 2022/6/6 14:28:38
10:28:49.288 -> sendCommandWithResponse: ====>
10:28:49.288 -> sendCommand: Command: $DT @*70
10:28:49.288 -> 
10:28:49.288 -> waitForResponse: $DT 20220606142844,V*47
10:28:49.288 -> 
10:28:49.288 -> waitForResponse: Panic! _swarmBacklog is full!
10:28:49.288 -> sendCommandWithResponse: <====
10:28:49.288 -> getDateTime returned: 2022/6/6 14:28:44
10:28:54.272 -> sendCommandWithResponse: ====>
10:28:54.272 -> sendCommand: Command: $DT @*70
10:28:54.272 -> 
10:28:54.272 -> waitForResponse: $DT 20220606142849,V*4a
10:28:54.272 -> 
10:28:54.272 -> waitForResponse: Panic! _swarmBacklog is full!
```

**Minimum reproducible example:**
```
#include <SparkFun_Swarm_Satellite_Arduino_Library.h> 

SWARM_M138 mySwarm;

#define swarmSerial Serial1

Swarm_M138_DateTimeData_t dateTime;
Swarm_M138_Error_e err;

void setup() {
  Serial.begin(115200);
  while (!Serial)
    ; // Wait for the user to open the Serial console
  Serial.println(F("Swarm Satellite example"));
  Serial.println();

  // Configure the Swarm modem
  mySwarm.enableDebugging(); // Uncomment this line to enable debug messages on Serial

  if (!mySwarm.begin(swarmSerial)) // Begin communication with the modem
  {
    Serial.println(F("Could not communicate with the modem. Please check the serial connections. Freezing..."));
    while (1);
  }
  mySwarm.setDateTimeRate(0);
  mySwarm.setGpsJammingIndicationRate(0);
  mySwarm.setGeospatialInfoRate(0);
  mySwarm.setGpsFixQualityRate(0);
  mySwarm.setPowerStatusRate(0);
  mySwarm.setReceiveTestRate(0);
  mySwarm.setMessageNotifications(false);
}

void loop() {

  err = mySwarm.getDateTime(&dateTime);

  if (err == SWARM_M138_SUCCESS)
  {
    Serial.print(F("getDateTime returned: "));
    Serial.print(dateTime.YYYY);
    Serial.print(F("/"));
    Serial.print(dateTime.MM);
    Serial.print(F("/"));
    Serial.print(dateTime.DD);
    Serial.print(F(" "));
    Serial.print(dateTime.hh);
    Serial.print(F(":"));
    Serial.print(dateTime.mm);
    Serial.print(F(":"));
    Serial.println(dateTime.ss);
  }
  else
  {
    Serial.print(F("Swarm communication error: "));
    Serial.print((int)err);
    Serial.print(F(" : "));
    Serial.println(mySwarm.modemErrorString(err)); // Convert the error into printable text
  }
  delay(5000);
}
```

**Comment by PaulZC** [comment]
Hi Adam (@adamgarbo ),

Qwick, untested, shoot-from-the-hip response:

What happens if you replace ```delay(5000);``` with:

```
delay(1000);
mySwarm.checkUnsolicitedMsg();
delay(1000);
mySwarm.checkUnsolicitedMsg();
delay(1000);
mySwarm.checkUnsolicitedMsg();
delay(1000);
mySwarm.checkUnsolicitedMsg();
delay(1000);
mySwarm.checkUnsolicitedMsg();
```

You shouldn't need to call checkUnsolicitedMsg if you're not using callbacks, but something is causing: one dateTime message to be skipped; the next call to getDateTime then picks up the skipped message (which is now five seconds 'old'). I think the fix will be to modify getDateTime so it checks for and reads a second dateTime message - if one exists.

Thanks!
Paul

**Comment by PaulZC** [comment]
And / Or increase this timeout limit to (say) 1100ms:

https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/blob/553f4ea946d06022afc9246016e2e792ff54e386/src/SparkFun_Swarm_Satellite_Arduino_Library.h#L77

**Comment by PaulZC** [comment]
Hi Adam,

OK. I understand what's happening...

- ```getDateTime``` is sending the **$DT @** request.
- The "sync lost" happens when the modem takes slightly longer than usual to repond - more than ```SWARM_M138_STANDARD_RESPONSE_TIMEOUT``` (1000) milliseconds.
- ```getDateTime``` returns a timeout.
- The modem then sends the **$DT** message and it is held in your processor's serial RX buffer.
- When you next call ```getDateTime``` , it sends another **$DT @** request and then immediately 'receives' (reads) the previous **$DT** message from the RX buffer.
- This continues ad infinitum. If another timeout happens, you end up further out of sync.

This isn't supposed to happen:
- There is [a piece of code](https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/blob/553f4ea946d06022afc9246016e2e792ff54e386/src/SparkFun_Swarm_Satellite_Arduino_Library.cpp#L5244-L5258) in ```sendCommandWithResponse``` (which calls ```sendCommand```) which is supposed to mop up any 'old' data from the buffer and put it into the backlog.
- Except the backlog is full because [everything is added to the backlog](https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/blob/553f4ea946d06022afc9246016e2e792ff54e386/src/SparkFun_Swarm_Satellite_Arduino_Library.cpp#L5345-L5368) (intentionally).
- The backlog is never emptied because you're not calling ```checkUnsolicitedMsg``` - and nor should you need to if you're not using callbacks.

The fix is, I think, going to be in two parts:
- I'll increase ```SWARM_M138_STANDARD_RESPONSE_TIMEOUT``` to say 1500 milliseconds, just to provide a bit more breathing room.
- I'll modify ```pruneBacklog``` so it only stores 'events' (messages) _for which a callback has been created_. That way the backlog should, in your case, always be empty.

I'll have some [release_candidate](https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/tree/release_candidate) code for you to try shortly.

Cheers,
Paul

**Comment by PaulZC** [comment]
Hi Adam (@adamgarbo ),

The fix is in... Please give release_candidate a try!

Paul

**Comment by adamgarbo** [comment]
Hi @PaulZC,

Perhaps as a quick follow-up to this issue, will the Swarm library ever be able to report a datetime that is not valid? From what I can gather, if the $DT command is issued and the modem doesn't have a valid datetime, it will come back with:
`Swarm communication error: 3 : Communication timeout`.

Cheers,
Adam

```
<--- Rebooted modem
09:23:02.465 -> sendCommandWithResponse: <====
09:23:02.465 -> sendCommandWithResponse: ====>
09:23:02.465 -> sendCommand: Command: $DT @*70
09:23:02.465 -> 
09:23:03.981 -> sendCommandWithResponse: <====
09:23:03.981 -> Swarm communication error: 3 : Communication timeout
09:23:09.001 -> sendCommandWithResponse: ====>
09:23:09.001 -> sendCommand: Command: $DT @*70
09:23:09.001 -> 
09:23:10.513 -> sendCommandWithResponse: <====
09:23:10.513 -> Swarm communication error: 3 : Communication timeout
09:23:15.564 -> sendCommandWithResponse: ====>
09:23:15.564 -> sendCommand: Command: $DT @*70
09:23:15.564 -> 
09:23:16.573 -> waitForResponse: $DT 20220608132315,V*41
09:23:16.573 -> 
09:23:16.573 -> sendCommandWithResponse: <====
09:23:16.573 -> getDateTime returned: 2022/6/8 13:23:15
09:23:21.625 -> sendCommandWithResponse: ====>
09:23:21.625 -> sendCommand: Command: $DT @*70
```

**Comment by PaulZC** [comment]
Hi Adam,

Thanks for the update. I'll release those changes shortly.

Re. "valid time": the timeouts look definitive. You _might_ get a response if you increase ```SWARM_M138_STANDARD_RESPONSE_TIMEOUT``` even further, but I don't recommend that. The manual says:

"no $DT messages will be sent by the device until the GPS has obtained a valid time reference to set its internal date and time, as indicated by the $M138 DATETIME*56 message. The valid flag will show V if the modem has acquired a valid time reference at least once since powering on."

I assume the "flag" is I (Invalid) initially and then changes to V (Valid) when it has GPS lock? Try requesting DT every second during power up. Does it go from timeouts to invalid time to valid time? (I'm assuming the flag is a copy of u-blox validTime, but I don't know.)

Cheers,
Paul
